---
- name: "apt upgrade packages"
  become: true
  apt:
    upgrade: "yes"
- name: "Install node.js"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install nodejs -y
- name: "install pm2 (process manager)"
  become: true
  npm:
    name: pm2
    state: present
    global: yes
    production: yes
