---
- name: "Create a directory"
  shell: mkdir ~/backend

- name: "Send artifact"
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend

- name: "Start the app"
  shell: |
    cd ~/backend 
    npm install
    pm2 stop default
    pm2 start npm -- start