---
- name: "Create a directory for backend"
  shell: mkdir ~/backend

- name: "Send backend artifact"
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend

- name: "Install"
  npm:
    path: ~/backend
    production: true
    global: true

- name: "Start things up"
  shell: cd ~/backend && pm2 stop all; pm2 start npm -- run start